version: '3'
services:
  mon-backend:
    image: ismailskr/sae-back:1.0
    ports:
      - "5050:5050"
    environment:
      - ENVIRONMENT=dev
    volumes:
      - data-volume:/modules/logs

  mon-frontend:
    image: ismailskr/sae-front:1.0
    ports:
      - "5052:50"  
    environment:
      - WS_BACK_URL=http://localhost:5050 

volumes:
  data-volume:
